---
development:
  DB_FILENAME: app/infrastructure/database/local/dev.db

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  APP_HOST: http://localhost:9292

app_test:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  APP_HOST: http://localhost:9292
  